// Copyright 2010-2014 RethinkDB, all rights reserved.
#ifndef CLUSTERING_ADMINISTRATION_ARTIFICIAL_TABLES_TABLE_CONFIG_HPP_
#define CLUSTERING_ADMINISTRATION_ARTIFICIAL_TABLES_TABLE_CONFIG_HPP_


#endif /* CLUSTERING_ADMINISTRATION_ARTIFICIAL_TABLES_TABLE_CONFIG_HPP_ */

